application:
  workdir: &workdir "/Users/kenyo/context/"
  environment:
    language: java
    extension: java
    commands:
      - "javac"
      - "%src%.%ext%"
      - "&&"
      - "java"
      - "-cp"
      - *workdir
      - "%src%"
  port: 9002